---

name: Build Lilypond Project

on:
  push:
    branches: [ "main" ]
    paths: '**.ly'
  pull_request:
    branches: [ "main" ]
    paths: '**.ly'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - run: wget -O lilypond.tar.gz https://gitlab.com/lilypond/lilypond/-/releases/v${{ vars.LILYPOND_VERSION }}/downloads/lilypond-${{ vars.LILYPOND_VERSION }}-linux-x86_64.tar.gz
      - run: tar xzf lilypond.tar.gz
      - run: ./lilypond-${{ vars.LILYPOND_VERSION }}/bin/lilypond -I openlilylib -dno-point-and-click ${{ vars.MAIN_FILE }}.ly
      - uses: actions/upload-artifact@v3
        with:
          name: Lilypond Output
          path: |
            ${{ vars.MAIN_FILE }}.pdf
            ${{ vars.MAIN_FILE }}.midi

  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Get current date (for tag)
        id: date
        run: echo "CURRENT=$(date +%F)" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: Lilypond Output
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.date.outputs.CURRENT }}
          body_path: changelog/CHANGELOG.latest
          files: |
            ${{ vars.MAIN_FILE }}.pdf
            ${{ vars.MAIN_FILE }}.midi
